server:
  port: 8080
spring:
  #  profiles:
  #    active: oyster
  mail:
    host: smtp.qq.com
    username: 403827354@qq.com
    password: mgysdtrrgxzsbhie
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  redis:
    database: 0
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/pixivic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cheerfun.dev
    type: com.alibaba.druid.pool.DruidDataSource
    batch:
      job:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 864000
  refreshInterval: 1800000
pixiv:
  oauth:
    client_id: KzEZED7aC0vird8jWyHM38mXjNTY
    client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
    refresh_token: 07FHA5xA6NkOIxIayqm3tZbJqxbypDJHrXguT7cazLI
    device_token: fb12e7c1945000850deb5f7001c02745
    config: /home/PIC/user2.json
saucenao:
  token:
    path: /home/PIC/saucenao.json
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-handlers-package: dev.cheerfun.pixivic.common.util.json
elasticsearch:
  ip: elasticsearch
apiLog:
  path: /var/log/nginx/api.pixivic.com
sensitiveWordList:
  path: /home/PIC/sensitive
