server:
  port: 8080
spring:
#  profiles:
#    active: mac
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mail:
    host: mail
    username: admin@cheerfun.dev
    password: Cheerfun.dev
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 99000
          timeout: 99000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    test-connection: true
    port: 465
  redis:
    jedis:
      pool:
        max-active: 16 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 16 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    cluster:
      nodes:
        - redis-1:6379
        - redis-2:6379
        - redis-3:6379
        - redis-4:6379
    password: Cheerfun.dev
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: root
    publisher-confirm-type:
  datasource:
    primary:
      jdbc_url: jdbc:mysql://mysql-biz:3306/pixivic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Cheerfun.dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 30
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 3000
      maxLifetime: 1800000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    secondary:
      jdbc_url: jdbc:mysql://mysql-crawler:3306/pixivic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Cheerfun.dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 40
      connectionTimeout: 3000
  cache:
    caffeine:
      spec: maximumSize=4096,expireAfterAccess=1800s
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员♥♥♥♥♥♥♥♥♥♥♥♥
  expirationTime: 86400
  refreshInterval: 10800000
pixiv:
  oauth:
    client_id: KzEZED7aC0vird8jWyHM38mXjNTY
    client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
    device_token: fb12e7c1945000850deb5f7001c02745
    config: /home/PIC/user2.json
saucenao:
  token:
    path: /home/PIC/saucenao.json
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-handlers-package: dev.cheerfun.pixivic.common.util.json
elasticsearch:
  ip: elasticsearch
apiLog:
  path: /home/PIC/log
sensitiveWordList:
  path: /home/PIC/sensitive
ssh:
  configPath: /home/PIC/ssh.conf
sitemap:
  savePath: /home/PIC/sitemap
  remoteSavePath: /home/PIC/sitemap
graphicsMagick:
  path: /usr/bin/gm
nsfw:
  modelPath: /home/PIC/nsfw.299x299.h5
chacha20:
  key: 生蚝是位兴趣使然的OTAKU
  nonce: PIXIVICJUST4
  counter: 21
recaptcha:
  secret: 6Le5lOIZAAAAAI34bH_axfWScwcKFnxUBNbpe60d
